language: cpp
addons:
  apt:
    packages:
      - libopenmpi-dev
      - openmpi-bin

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq g++-4.8
 - export CXX="g++-4.8"
 - mkdir ~/projects/
 - git clone https://github.com/jrising/openworld.git ~/projects/openworld
 - git clone https://github.com/jrising/opendims.git ~/projects/opendims

script:
 - make
