language: cpp
addons:
  apt:
    packages:
      - libopenmpi-dev
      - openmpi-bin
compiler:
  - gcc
  
install:
 - mkdir ~/projects/
 - git clone https://github.com/jrising/openworld.git ~/projects/openworld
 - git clone https://github.com/jrising/opendims.git ~/projects/opendims
script:
 - make
